### ISSUE TITLE
What resources is required?

### ISSUE THREAD

**Issue by thomas-alrek** [madmonkey1907/hakchi#14]
Which of the resources does the application expect to have available when running? 

Like the bin folder, 3rdparty folder etc?

**Comment by madmonkey1907** [comment]
bin, mod, and data directories are needed. you can compile files in data yourself from uboot sources, or grab them from win32 release. on startup, app searches directory containing executable for bin directory, and if not found, tries to locate that directory in up to 4 directories above. mod directory should be taken from repo rather that win32 release, or else file permissions will not be correct.
