### ISSUE TITLE
Compiling under GNU/Linux

### ISSUE THREAD

**Issue by sniperpon** [madmonkey1907/hakchi#2]
How did you handle compiling 3rd party dependencies? I get a "No rule to make target '3rdparty/sunxi-tools/fel.c'" from make under Arch.

Or is it for naught-- what did you write the UI in?

Awesome work on this btw :)

**Comment by madmonkey1907** [comment]
Did you forget git submodule init? It needs qt4 and libusb1.

**Comment by vandre** [comment]
@sniperpon
git submodule init wasn't working for me with a fresh clone. It looks like the urls for the 3rd party libraries are incorrect: I had to manually update my .git/config
```

[submodule "3rdparty/mkbootimg"]
	url = https://github.com/osm0sis/mkbootimg.git
[submodule "3rdparty/sunxi-tools"]
	url = https://github.com/linux-sunxi/sunxi-tools.git
```

After this then I did:

```
git submodule init
git submodule update
```

**Comment by madmonkey1907** [comment]
they are correct. you need to have ssh key attached to your account.
