### ISSUE TITLE
Transifex language translation crowdsourcing services

### ISSUE THREAD

**Issue by Hedda** [madmonkey1907/hakchi#24]
Suggest that you setup a new project for Hakchi (and NES/Famicom Mini) on Transifex translation services to get crowdsourced translations from your community.

https://en.wikipedia.org/wiki/Transifex

Many popular open source software projects use Transifex workflows to get free string language translations from their communities.

Example of an open source project using Transifex for many years is Kodi as you can read here:
https://kodi.tv/new-translation-service/
and here:
http://kodi.wiki/view/Translation_System

For end-users wanting to help out with the project using Transifex to translate strings is as easy as using a wiki.

Users just need to register an account for free on Transifex then join the project for the languages they know and begin to translate strings they understand.

All you need to do is point to files on GitHub you want translating and then copy/pull them from Transifex on a regular bases (usually before each release).

**Comment by madmonkey1907** [comment]
no spam please

**Comment by Hedda** [comment]
Not spam. I have no personal connection to Transifex, and using it is free so what woul I gain by spamming. This is just a recommendation as I think it would be cool to have NES Mini hacks/mods that translate it the GUI to more languages.

I use Kodi and it have translations for over 70+ languages being done through Transifex https://www.transifex.com/teamxbmc/kodi-main/

I just wanted to recommend that if Hakchi use Transifex then the projects can get translations in a smoother way through Transifex instead of through pull requests here on GitHub..

**Comment by madmonkey1907** [comment]
well, if that's not a spam, consider it a compliment, it's very well written. that said, I have zero interest translating this to other languages, technically, it's already translated(english is not my native language).
if you or someone else wants it translated, consider submitting a pull request, and it will be merged.
