### ISSUE TITLE
Build instructions for Windows / Add a build of the latest commit

### ISSUE THREAD

**Issue by DeadlySystem** [madmonkey1907/hakchi#26]
Hi, I'm trying to dump the NAND of my NES Mini on Windows 7. I've seen the code for NAND dumping is in the current code, but the published releases are very outdated. Can you provide an up-to-date build and/or build instructions for Windows please? Thanks!

**Comment by huguenin** [comment]
*bump*

**Comment by madmonkey1907** [comment]
whoopsie. current build uploaded. unfortunately, I have no idea how to compile it on windows. I'm using [mxe](http://mxe.cc/) on debian.

**Comment by DeadlySystem** [comment]
Wow, didn't think you'd ever get back after all that time - great to hear from you :) In the mean time I've experimented with compilation unter Linux in a Docker container and successfully forwarded the GUI to Windows using Xming (and USB forwarding into the container). I've never managed to build the helper files though - just took those from the existing release.

The current Windows build opens and quickly shows the GUI but then immediately "stops working", i.e. segfault (NES Mini is not plugged in) - but it's a pre-release after all, so don't worry about it :) What I would fine more interesting is how to work with the NAND dump. I've managed to dump it with my container setup and I've also successfully extracted the key file from the kernel dump, but my attempts to mount it have failed. Do you have any advice on that?

**Comment by madmonkey1907** [comment]
it seems to work for me under xp vm. it does segfault under wine though, no idea why.
for nand dump, look at the comments here https://github.com/madmonkey1907/hakchi/commit/669a8ee56ba6d66a90126756cd84f52ae0a5bc83

**Comment by DeadlySystem** [comment]
Thank you very much for referencing that commit @madmonkey1907 !!! Using the info you provided there, I've successfully decrypted my NAND and extracted the games. I've dockerized all the tools for easy use: https://github.com/DeadlySystem/ninspect
Thank you for making this possible!

**Comment by DeadlySystem** [comment]
...and now I've also added docker-hakchi, which is what I used to run latest hakchi on Windows inside a Debian container: https://github.com/DeadlySystem/ninspect/tree/master/docker-hakchi this is my complete solution :)
