### ISSUE TITLE
Option to dump/extract rootfs

### ISSUE THREAD

**Issue by isage** [madmonkey1907/hakchi#29]
Can you please add one?

**Comment by madmonkey1907** [comment]
I can, but not right now. most likely it'll still read the whole nand first, as random reads trough uboot are really gross.
meanwhile, https://github.com/DeadlySystem/ninspect
maybe it's what you need?

**Comment by isage** [comment]
It is and it's not) I've already extracted and decrypted my rootfs thanks to your comments here: https://github.com/madmonkey1907/hakchi/commit/669a8ee56ba6d66a90126756cd84f52ae0a5bc83

And yeah, dump full nand, then extract and (optionally)decrypt partitions. It's just nicer to have it all in one place.

**Comment by madmonkey1907** [comment]
just to check, you mean for windows, right? because I do have script for linux, which is probably why I'm not really enthusiastic enough to do it for windows :)

**Comment by isage** [comment]
Nah, linux/osx. I don't have windows)

**Comment by madmonkey1907** [comment]
good :)
https://gist.github.com/madmonkey1907/db0a9fce59523ce0ceeb7fa91c292aa4
