### ISSUE TITLE
busybox latest/ disappeared

### ISSUE THREAD

**Issue by bmx** [madmonkey1907/hakchi#3]
I had to use 

http://web.archive.org/web/20161104040144/http://busybox.net/downloads/binaries/latest/busybox-armv7l

**Comment by potyl** [comment]
This link also works: https://busybox.net/downloads/binaries/1.21.1/busybox-armv7l

**Comment by madmonkey1907** [comment]
fixed by d359d6cc953e472320674187a76f8942e7241bac
