### ISSUE TITLE
Proposal: add support for g_ether or g_mass_storage

### ISSUE THREAD

**Issue by isage** [madmonkey1907/hakchi#31]
Subj. I think that g_ether+ssh/ftp would be easier to set up, however g_mass_storage would be more universal (but it requires unmounting partition on device and fat support)

**Comment by madmonkey1907** [comment]
possible, but cannot provide any eta. currently looking into mass storage usb-host support.

**Comment by isage** [comment]
Wouldn't it be easier to support SDC? USB would require power input separation.

**Comment by madmonkey1907** [comment]
Nes mini doesn't have a battery, so no power separation is required. Any otg hub will work. I compiled in g_ether, but I didn't try to configure it.

**Comment by madmonkey1907** [comment]
https://github.com/DanTheMan827-Hakchi/rndis.hmod
ssh works with it. there is a problem with linux when rndis crashes, but it works after several retries.
