### ISSUE TITLE
clovershell-client for linux

### ISSUE THREAD

**Issue by timehlers** [madmonkey1907/hakchi#32]
Hi,

I'd like to ask if anyone, maybe you @madmonkey1907 :), is willing to port the clovershell-client. I actually don't completely understand the situation, so I don't really get how generally people using "hakchi" put files on the NES/SNES, since in FEL mode you don't have access to the filesystems. What I do understand is, that hakchi2 is using a daemon "clovershell-daemon" on the NES/SNES side and the client on the windows (.NET 3.5) side. The problem is, that not only hakchi2 itself is using in mono unimplemented functions, so that mono+hachi2 is not working ([Does not work in wine](https://github.com/ClusterM/hakchi2/issues/533)), but also the simple [clovershell-client](https://github.com/ClusterM/clovershell-client) does not work on linux mono.

I have tried to debug this today. There is one issue for mono unfixed: [Fixed object disposed exception in mono](https://github.com/svn2github/libusbdotnet/commit/4d69ad38a5bf17a72600cd748e4319c1bea8c7df). But updating this, does not fix the problem. The first USB-write is working (I see the request in usbmon in a tcpdump), but then everything hangs, also read does not go through.

I am a bit stuck now. It would be nice to have shell/filetransfer to NES/SNES from a linux system.

Best

Tim

**Comment by isage** [comment]
See https://github.com/madmonkey1907/hakchi/issues/31
ssh/ftp or mass storage would be easier and more crossplatform to use.
And would't require porting

**Comment by timehlers** [comment]
You are absolutely right, only that there is already a complete implementation on server side and (only on linux non-working) client. This client includes a working ftp/telnet implementation. We just need to port the client or find the problem on mono.

Of course it would be nice to have a native solution, but another advantage to use at least the server part from hakchi2 is, that there is not too much of redundant, dual world evolution on this tool.

BTW: I still did not get how one exchanges data with hakchi (without hakchi2). Do I need to dump whole flash, mount loopback and flash everything back?

**Comment by madmonkey1907** [comment]
Sorry, I won't work on clovershell client. I suspect there is probably easier way to do it with socat. g_ether will probably work nicely as well.
You don't need to dump anything except key-file. As for copying, I posted some rudimentary tutorial on how to do it way back then, it should still be relevant. Should be possible to find with google. Typing from the phone, maybe will link later.

**Comment by timehlers** [comment]
Hi,

ok, I understand. If you see another solution, like g_ether or socat to be the better way, I would also be happy. Since I did not find any tutorial (I always find dump tutorials for hakchi2 when searching on google), I would appreciate to get a link. Maybe you could also put this tutorial in the README.md for others?

Thanks!

**Comment by madmonkey1907** [comment]
https://github.com/DanTheMan827-Hakchi/rndis.hmod
ssh works with it. there is a problem with linux when rndis crashes, but it works after several retries.
